# Generated by Django 4.2.7 on 2026-04-08 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('galaxy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='tournament.galaxy')),
            ],
            options={
                'ordering': ['galaxy', 'name'],
                'unique_together': {('name', 'galaxy')},
            },
        ),
        migrations.CreateModel(
            name='SubMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='Display order of this sub-match within the parent match.')),
                ('notes', models.CharField(blank=True, help_text='Optional notes, e.g. score or remarks.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_matches', to='tournament.match')),
                ('player_1', models.ForeignKey(help_text='Must belong to galaxy_1 of the parent match.', on_delete=django.db.models.deletion.CASCADE, related_name='sub_matches_as_p1', to='tournament.player')),
                ('player_2', models.ForeignKey(help_text='Must belong to galaxy_2 of the parent match.', on_delete=django.db.models.deletion.CASCADE, related_name='sub_matches_as_p2', to='tournament.player')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_sub_matches', to='tournament.player')),
            ],
            options={
                'ordering': ['match', 'order'],
            },
        ),
    ]
