# Generated by Django 4.2.7 on 2026-04-08 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_player_submatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='submatch',
            name='player_1b',
            field=models.ForeignKey(blank=True, help_text='Doubles partner; must belong to galaxy_1 (≠ player_1).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_matches_as_p1b', to='tournament.player'),
        ),
        migrations.AddField(
            model_name='submatch',
            name='player_2b',
            field=models.ForeignKey(blank=True, help_text='Doubles partner; must belong to galaxy_2 (≠ player_2).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_matches_as_p2b', to='tournament.player'),
        ),
        migrations.AddField(
            model_name='submatch',
            name='sub_match_type',
            field=models.CharField(choices=[('singles', 'Singles'), ('doubles', 'Doubles')], default='singles', max_length=10),
        ),
        migrations.AlterField(
            model_name='submatch',
            name='notes',
            field=models.CharField(blank=True, help_text='Optional notes, e.g. score "21-18, 21-15" or remarks.', max_length=255),
        ),
    ]
