# Generated by Django 4.2.7 on 2026-04-08 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_submatch_player_1b_submatch_player_2b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submatch',
            name='winning_side_team',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Side 1 (Galaxy 1)'), (2, 'Side 2 (Galaxy 2)')], help_text='Team sub-matches only — which galaxy side won.', null=True),
        ),
        migrations.AlterField(
            model_name='submatch',
            name='player_1',
            field=models.ForeignKey(blank=True, help_text='Singles/doubles only — must belong to galaxy_1.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_matches_as_p1', to='tournament.player'),
        ),
        migrations.AlterField(
            model_name='submatch',
            name='player_2',
            field=models.ForeignKey(blank=True, help_text='Singles/doubles only — must belong to galaxy_2.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_matches_as_p2', to='tournament.player'),
        ),
        migrations.AlterField(
            model_name='submatch',
            name='sub_match_type',
            field=models.CharField(choices=[('singles', 'Singles'), ('doubles', 'Doubles'), ('team', 'Team')], default='singles', max_length=10),
        ),
        migrations.CreateModel(
            name='SubMatchTeamPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.PositiveSmallIntegerField(choices=[(1, 'Side 1 (Galaxy 1)'), (2, 'Side 2 (Galaxy 2)')])),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_sub_matches', to='tournament.player')),
                ('sub_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_players', to='tournament.submatch')),
            ],
            options={
                'ordering': ['sub_match', 'side', 'player'],
                'unique_together': {('sub_match', 'player')},
            },
        ),
    ]
